### ISSUE TITLE
error when starting rails server after upgrading to El Capitan

### ISSUE THREAD

**Issue by abigure** [kubo/ruby-oci8#112]
Hi 

Thank you for ruby-oci8.

I got error when starting rails server after upgrading to El Capitan. And also browse all issues and still can't solve the problem.  Following is the message:

```bash
$ gem install ruby-oci8 --version='2.1.3'
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-oci8:
	ERROR: Failed to build gem native extension.

    /Users/sean/.rvm/rubies/ruby-1.9.3-p551/bin/ruby -r ./siteconf20151209-11199-rebu7u.rb extconf.rb
checking for load library path...
  DYLD_LIBRARY_PATH is not set.
checking for cc... ok
checking for gcc... yes
checking for LP64... yes
checking for sys/types.h... yes
checking for ruby header... ok
Get the version of Oracle from SQL*Plus... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/sean/.rvm/rubies/ruby-1.9.3-p551/bin/ruby
	--with-instant-client
	--without-instant-client
/Users/sean/.rvm/gems/ruby-1.9.3-p551/gems/ruby-oci8-2.1.3/ext/oci8/oraconf.rb:758:in `get_version': RuntimeError (RuntimeError)
	from /Users/sean/.rvm/gems/ruby-1.9.3-p551/gems/ruby-oci8-2.1.3/ext/oci8/oraconf.rb:707:in `initialize'
	from /Users/sean/.rvm/gems/ruby-1.9.3-p551/gems/ruby-oci8-2.1.3/ext/oci8/oraconf.rb:319:in `new'
	from /Users/sean/.rvm/gems/ruby-1.9.3-p551/gems/ruby-oci8-2.1.3/ext/oci8/oraconf.rb:319:in `get'
	from extconf.rb:18:in `<main>'
---------------------------------------------------
Error Message:
  cannot get Oracle version from sqlplus
Backtrace:
  /Users/sean/.rvm/gems/ruby-1.9.3-p551/gems/ruby-oci8-2.1.3/ext/oci8/oraconf.rb:758:in `get_version'
  /Users/sean/.rvm/gems/ruby-1.9.3-p551/gems/ruby-oci8-2.1.3/ext/oci8/oraconf.rb:707:in `initialize'
  /Users/sean/.rvm/gems/ruby-1.9.3-p551/gems/ruby-oci8-2.1.3/ext/oci8/oraconf.rb:319:in `new'
  /Users/sean/.rvm/gems/ruby-1.9.3-p551/gems/ruby-oci8-2.1.3/ext/oci8/oraconf.rb:319:in `get'
  extconf.rb:18:in `<main>'
---------------------------------------------------
See:
 * http://ruby-oci8.rubyforge.org/en/HowToInstall.html
 * http://ruby-oci8.rubyforge.org/en/ReportInstallProblem.html


extconf failed, exit code 1

Gem files will remain installed in /Users/sean/.rvm/gems/ruby-1.9.3-p551/gems/ruby-oci8-2.1.3 for inspection.
Results logged to /Users/sean/.rvm/gems/ruby-1.9.3-p551/extensions/x86_64-darwin-14/1.9.1/ruby-oci8-2.1.3/gem_make.out
```

**Comment by abigure** [comment]
Please ignore this issue. I installed ruby-oci8 2.2.1 with newest instant client then success. Thanks for your time.
