### ISSUE TITLE
ruby-oci8 -v '2.1.8' with macOS Sierra 10.12.3 is possible?

### ISSUE THREAD

**Issue by rafaeldl** [kubo/ruby-oci8#164]
Instantclient instalation ok:

```
$ sqlplus -v

SQL*Plus: Release 12.1.0.2.0 Production
```

Command:

```
$ gem install ruby-oci8 -v '2.1.8'
```

or...

```
$ DYLD_LIBRARY_PATH=/usr/local/opt/oracle/instantclient_12_1/lib gem install ruby-oci8 -v '2.1.8'
```

Error:

```
gem install ruby-oci8 -v '2.1.8'
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-oci8:
	ERROR: Failed to build gem native extension.

    current directory: /Users/rafaeldl/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.1.8/ext/oci8
/Users/rafaeldl/.rbenv/versions/2.4.0/bin/ruby -r ./siteconf20170327-10337-ocxlz2.rb extconf.rb
checking for load library path... 
  DYLD_LIBRARY_PATH is not set.
checking for cc... ok
checking for gcc... yes
checking for LP64... yes
checking for sys/types.h... yes
checking for ruby header... ok
Get the version of Oracle from SQL*Plus... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/rafaeldl/.rbenv/versions/2.4.0/bin/$(RUBY_BASE_NAME)
	--with-instant-client
	--without-instant-client
/Users/rafaeldl/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.1.8/ext/oci8/oraconf.rb:762:in `get_version': RuntimeError (RuntimeError)
	from /Users/rafaeldl/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.1.8/ext/oci8/oraconf.rb:711:in `initialize'
	from /Users/rafaeldl/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.1.8/ext/oci8/oraconf.rb:320:in `new'
	from /Users/rafaeldl/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.1.8/ext/oci8/oraconf.rb:320:in `get'
	from extconf.rb:18:in `<main>'
---------------------------------------------------
Error Message:
  cannot get Oracle version from sqlplus
Backtrace:
  /Users/rafaeldl/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.1.8/ext/oci8/oraconf.rb:762:in `get_version'
  /Users/rafaeldl/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.1.8/ext/oci8/oraconf.rb:711:in `initialize'
  /Users/rafaeldl/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.1.8/ext/oci8/oraconf.rb:320:in `new'
  /Users/rafaeldl/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.1.8/ext/oci8/oraconf.rb:320:in `get'
  extconf.rb:18:in `<main>'
---------------------------------------------------
See:
 * http://rubydoc.info/gems/ruby-oci8/file/docs/install-full-client.md for Oracle full client
 * http://rubydoc.info/gems/ruby-oci8/file/docs/install-instant-client.md for Oracle instant client
 * http://ruby-oci8.rubyforge.org/en/file.report-installation-issue.html to report an issue.


To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/rafaeldl/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-16/2.4.0-static/ruby-oci8-2.1.8/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/rafaeldl/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.1.8 for inspection.
Results logged to /Users/rafaeldl/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-16/2.4.0-static/ruby-oci8-2.1.8/gem_make.out
```

Environment:

```
$ env
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/8x/tn78g4ds577cp34q35zj2xdc0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.xy1TD68Exv/Render
TERM_PROGRAM_VERSION=388
OLDPWD=/usr/local/opt/oracle/instantclient_12_1
TERM_SESSION_ID=0E2667A8-F0D2-4473-9ED8-BDB980C7C059
USER=rafaeldl
OCI_DIR=/usr/local/opt/oracle/instantclient_12_1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.6nePQ8TZbm/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x47
PATH=/Users/rafaeldl/Projetos/libs/google-cloud-sdk/bin:/Users/rafaeldl/.rbenv/shims:/Users/rafaeldl/Projetos/libs/google-cloud-sdk/bin:/Users/rafaeldl/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/oracle/instantclient_12_1
PWD=/Users/rafaeldl
LANG=pt_BR.UTF-8
XPC_FLAGS=0x0
RBENV_SHELL=bash
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/rafaeldl
LOGNAME=rafaeldl
ORACLE_HOME=/usr/local/opt/oracle/instantclient_12_1
_=/usr/bin/ENV

```

I've tried this, but it did not work:

```
$ DYLD_LIBRARY_PATH=/usr/local/opt/oracle/instantclient_12_1/lib export DYLD_LIBRARY_PATH
```

can anybody help me?

Thanks.

**Comment by kubo** [comment]
The followings may help you. I haven't checked whether it works.
```shell
$ cd /Users/rafaeldl/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.1.8/ext/oci8
$ curl -LO https://raw.githubusercontent.com/kubo/ruby-oci8/master/ext/oci8/oraconf.rb # replace with the latest oraconf.rb
$ cd ../..
$ gem build ruby-oci8.gemspec  # rebuild ruby-oci8 gem including the latest oraconf.rb
$ mv ruby-oci8-2.1.8.gem ~/
$ cd
$ gem install ./ruby-oci8-2.1.8.gem
```

**Comment by rafaeldl** [comment]
I was able to compile GEM, but now it is presenting the following message when I run the application: 

oci8.c:696:in oci8lib_210.bundle: ORA-21561: OID generation failed (OCIError)

```
=> Booting WEBrick
=> Rails 3.2.19 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Warning: NLS_LANG is not set. fallback to US7ASCII.
/Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/poseidon-55807a56d972/config/initializers/exec_auto.rb:3: warning: already initialized constant EXEC_AUTO
/Users/rafaeldl/Projetos/poseidon_khronos/config/initializers/exec_auto.rb:4: warning: previous definition of EXEC_AUTO was here
Exiting
oci8.c:696:in oci8lib_210.bundle: ORA-21561: OID generation failed (OCIError)
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby-oci8-2.1.8/lib/oci8/oci8.rb:149:in `initialize'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-oracle_enhanced-adapter-1.4.3/lib/active_record/connection_adapters/oracle_enhanced_oci_connection.rb:326:in `new'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-oracle_enhanced-adapter-1.4.3/lib/active_record/connection_adapters/oracle_enhanced_oci_connection.rb:326:in `new_connection'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-oracle_enhanced-adapter-1.4.3/lib/active_record/connection_adapters/oracle_enhanced_oci_connection.rb:436:in `initialize'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-oracle_enhanced-adapter-1.4.3/lib/active_record/connection_adapters/oracle_enhanced_oci_connection.rb:24:in `new'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-oracle_enhanced-adapter-1.4.3/lib/active_record/connection_adapters/oracle_enhanced_oci_connection.rb:24:in `initialize'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-oracle_enhanced-adapter-1.4.3/lib/active_record/connection_adapters/oracle_enhanced_connection.rb:9:in `new'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-oracle_enhanced-adapter-1.4.3/lib/active_record/connection_adapters/oracle_enhanced_connection.rb:9:in `create'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-oracle_enhanced-adapter-1.4.3/lib/active_record/connection_adapters/oracle_enhanced_base_ext.rb:13:in `oracle_enhanced_connection'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `loop'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `block in connection'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in `connection'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in `retrieve_connection'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/model_schema.rb:224:in `table_exists?'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/attribute_methods/primary_key.rb:75:in `get_primary_key'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/attribute_methods/primary_key.rb:60:in `reset_primary_key'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/attribute_methods/primary_key.rb:49:in `primary_key'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/attribute_assignment.rb:13:in `attributes_protected_by_default'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activemodel-3.2.19/lib/active_model/mass_assignment_security.rb:216:in `block in protected_attributes_configs'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activemodel-3.2.19/lib/active_model/mass_assignment_security.rb:188:in `yield'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activemodel-3.2.19/lib/active_model/mass_assignment_security.rb:188:in `protected_attributes'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activemodel-3.2.19/lib/active_model/mass_assignment_security.rb:118:in `block in attr_protected'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activemodel-3.2.19/lib/active_model/mass_assignment_security.rb:117:in `each'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activemodel-3.2.19/lib/active_model/mass_assignment_security.rb:117:in `attr_protected'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/poseidon-55807a56d972/lib/poseidon/protheus/base.rb:65:in `set_config'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/poseidon-55807a56d972/lib/poseidon/protheus/entity_manager.rb:29:in `block in get_class'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/poseidon-55807a56d972/lib/poseidon/protheus/entity_manager.rb:26:in `class_eval'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/poseidon-55807a56d972/lib/poseidon/protheus/entity_manager.rb:26:in `get_class'
	from /Users/rafaeldl/Projetos/poseidon_khronos/app/models/approval_observer.rb:6:in `<class:ApprovalObserver>'
	from /Users/rafaeldl/Projetos/poseidon_khronos/app/models/approval_observer.rb:4:in `<top (required)>'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:469:in `load'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:469:in `block in load_file'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:639:in `new_constants_in'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:468:in `load_file'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:353:in `require_or_load'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:502:in `load_missing_constant'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:192:in `block in const_missing'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:190:in `each'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:190:in `const_missing'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/inflector/methods.rb:230:in `block in constantize'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/inflector/methods.rb:229:in `each'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/inflector/methods.rb:229:in `constantize'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/core_ext/string/inflections.rb:54:in `constantize'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activemodel-3.2.19/lib/active_model/observing.rb:86:in `instantiate_observer'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activemodel-3.2.19/lib/active_model/observing.rb:59:in `block in instantiate_observers'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activemodel-3.2.19/lib/active_model/observing.rb:59:in `each'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activemodel-3.2.19/lib/active_model/observing.rb:59:in `instantiate_observers'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/railtie.rb:123:in `block (2 levels) in <class:Railtie>'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/lazy_load_hooks.rb:25:in `each'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/railtie.rb:122:in `block in <class:Railtie>'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/lazy_load_hooks.rb:34:in `call'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/lazy_load_hooks.rb:34:in `execute_hook'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/lazy_load_hooks.rb:42:in `each'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.19/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `run'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `each'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.19/lib/rails/application.rb:136:in `initialize!'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /Users/rafaeldl/Projetos/poseidon_khronos/config/environment.rb:5:in `<top (required)>'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
	from /Users/rafaeldl/Projetos/poseidon_khronos/config.ru:3:in `block in <main>'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.4.7/lib/rack/builder.rb:51:in `instance_eval'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initialize'
	from /Users/rafaeldl/Projetos/poseidon_khronos/config.ru:in `new'
	from /Users/rafaeldl/Projetos/poseidon_khronos/config.ru:in `<main>'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.4.7/lib/rack/builder.rb:40:in `eval'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.4.7/lib/rack/builder.rb:40:in `parse_file'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.4.7/lib/rack/server.rb:200:in `app'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.19/lib/rails/commands/server.rb:46:in `app'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.4.7/lib/rack/server.rb:304:in `wrapped_app'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.4.7/lib/rack/server.rb:254:in `start'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.19/lib/rails/commands/server.rb:70:in `start'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.19/lib/rails/commands.rb:55:in `block in <top (required)>'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.19/lib/rails/commands.rb:50:in `tap'
	from /Users/rafaeldl/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.19/lib/rails/commands.rb:50:in `<top (required)>'
	from /Users/rafaeldl/Projetos/poseidon_khronos/script/rails:6:in `require'
	from /Users/rafaeldl/Projetos/poseidon_khronos/script/rails:6:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

**Comment by rafaeldl** [comment]
I found the solution here https://github.com/joeferner/node-oracle/issues/47#issuecomment-38309484

```
$ echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
```

Congratulations on your work building this gem!

Thanks a lot!!

**Comment by rafaeldl** [comment]
Working!!!
