### ISSUE TITLE
OCI8 Load Error

### ISSUE THREAD

**Issue by estorilphil** [kubo/ruby-oci8#199]
Hi I'm getting the following error even tho I have Ruby-oci8 gem (2.2.5.1 x64-mingw32, 2.2.2 x64-mingw32) installed.  I have Ruby version 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32] and this is running on Windows 7.  Thanks for helping..

LoadError: OCI.DLL: 126(The specified module could not be found.  )
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.2.5.1-x64-mingw32/lib/oci8.rb:107:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):1
        from C:/Ruby24-x64/bin/irb.cmd:19:in `<main>'

**Comment by kubo** [comment]
What type of Oracle client and what version of Oracle client do you use?
If it is Oracle instant client, did you install Microsoft Visual C++ Redistributable Package required by the instant client?
See: https://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/install-instant-client.md#Windows

**Comment by estorilphil** [comment]
Hi Kubo, thanks for responding to my issue.  I have Instance Client (12.2) installed and it is referenced in the "path" variable.  And I do have visual C++ redistributable (2013) installed as well.  However I'd just noticed I'd installed the Win32 version (I have 64bit Windows 7) of Instant Client (the StackOverflow page I found at the time referenced Instant-Client & Redistributable but the win32 version of redist).  So I will reinstall the Win64 version of instant client and try again..  thanx..

Philip
