### ISSUE TITLE
OCIError: OCI Library Initialization Error - /Users/username/instantclient_12_2/libclntsh.dylib.12.1

### ISSUE THREAD

**Issue by mattretzer** [kubo/ruby-oci8#207]
Hello, I have been checking and re-checking my environment vars re: this error, but am unable to resolve so far.
Can reproduce in irb via 'require 'oci8'
Mac OS 10.13.6

```
OCIError: OCI Library Initialization Error - /Users/username/instantclient_12_2/libclntsh.dylib.12.1
	from oci8lib.c:156:in oci8lib_230.bundle
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/username/.gem/ruby/2.3.0/gems/ruby-oci8-2.2.1/lib/oci8.rb:72:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from (irb):1
	from /usr/bin/irb:11:in `<main>'
```

any suggestions?

**Comment by kubo** [comment]
I got same result when I use `/usr/bin/ruby`. Could you try ruby installed by [rbenv](https://github.com/rbenv/rbenv#homebrew-on-macos)?
I don't know why `/usr/bin/ruby` cannot load oci8.

**Comment by mattretzer** [comment]
Ruby installed by rbenv works great, thanks for the tip!
And thank you very much for replying so quickly!
