### ISSUE TITLE
Segmentation fault when loaded after 'pg'

### ISSUE THREAD

**Issue by joelw** [kubo/ruby-oci8#71]
Hi!

I'm trying to use ruby-oci8 2.1.7 and pg 0.17.1 at the same time and have found that ruby-oci8 crashes/hangs if it is loaded after pg.

Minimal example program:

```ruby
gem 'ruby-oci8'
require 'pg'
require 'oci8'
require 'sequel'

db=OCI8.new('user', 'pass', 'db')

db.exec('select * from schema.table where rownum <= 1') do |row|
  puts row.join ','
end
```

If `require 'pg'` is commented out, it works fine.

On OS X 10.10.2, it produces the crash dump below. On Linux it causes a hang that requires a kill -9 to resolve. I've tried it under both Ruby 2.1.3 and 2.1.5.

Any ideas? Some sort of library symbol conflict?

Thanks!
Joel

Crash dump:

```
/Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8/oci8.rb:148: [BUG] Segmentation fault at 0x00000000000000
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.

-- Control frame information -----------------------------------------------
c:0005 p:---- s:0027 e:000026 CFUNC  :server_attach
c:0004 p:0396 s:0022 e:000021 METHOD /Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8/oci8.rb:148 [FINISH]
c:0003 p:---- s:0011 e:000010 CFUNC  :new
c:0002 p:0049 s:0005 E:001e60 EVAL   test.rb:6 [FINISH]
c:0001 p:0000 s:0002 E:000338 TOP    [FINISH]

test.rb:6:in `<main>'
test.rb:6:in `new'
/Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8/oci8.rb:148:in `initialize'
/Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8/oci8.rb:148:in `server_attach'

-- C level backtrace information -------------------------------------------
0   libruby.2.1.0.dylib                 0x000000010ceffff0 rb_vm_bugreport + 144
1   libruby.2.1.0.dylib                 0x000000010cdb1251 report_bug + 305
2   libruby.2.1.0.dylib                 0x000000010cdb1114 rb_bug + 180
3   libruby.2.1.0.dylib                 0x000000010ce8204c sigsegv + 156
4   libsystem_platform.dylib            0x00007fff951f3f1a _sigtramp + 26
5   LDAP                                0x00007fff99c0d141 ldap_first_entry + 12
6   ???                                 0x00007fff52e83c40 0x0 + 140734584339520

-- Other runtime information -----------------------------------------------

* Loaded script: test.rb

* Loaded features:

    0 enumerator.so
    1 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/x86_64-darwin14.0/enc/encdb.bundle
    2 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/x86_64-darwin14.0/enc/trans/transdb.bundle
    3 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/x86_64-darwin14.0/rbconfig.rb
    4 thread.rb
    5 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/x86_64-darwin14.0/thread.bundle
    6 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/compatibility.rb
    7 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/defaults.rb
    8 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/deprecate.rb
    9 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/errors.rb
   10 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/version.rb
   11 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/requirement.rb
   12 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/platform.rb
   13 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/basic_specification.rb
   14 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/stub_specification.rb
   15 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/util/stringio.rb
   16 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb
   17 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/exceptions.rb
   18 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb
   19 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/monitor.rb
   20 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb
   21 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems.rb
   22 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb
   23 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/path_support.rb
   24 /Users/joel/.rvm/gems/ruby-2.1.3/extensions/x86_64-darwin-14/2.1.0/pg-0.17.1/pg_ext.bundle
   25 /Users/joel/.rvm/gems/ruby-2.1.3/gems/pg-0.17.1/lib/pg/exceptions.rb
   26 /Users/joel/.rvm/gems/ruby-2.1.3/gems/pg-0.17.1/lib/pg/constants.rb
   27 /Users/joel/.rvm/gems/ruby-2.1.3/gems/pg-0.17.1/lib/pg/connection.rb
   28 /Users/joel/.rvm/gems/ruby-2.1.3/gems/pg-0.17.1/lib/pg/result.rb
   29 /Users/joel/.rvm/gems/ruby-2.1.3/gems/pg-0.17.1/lib/pg.rb
   30 /Users/joel/.rvm/gems/ruby-2.1.3/extensions/x86_64-darwin-14/2.1.0/ruby-oci8-2.1.7/oci8lib_210.bundle
   31 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/exception.rb
   32 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/syntax_error.rb
   33 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/x86_64-darwin14.0/psych.bundle
   34 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/x86_64-darwin14.0/stringio.bundle
   35 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/omap.rb
   36 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/set.rb
   37 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/class_loader.rb
   38 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/x86_64-darwin14.0/strscan.bundle
   39 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/scalar_scanner.rb
   40 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/nodes/node.rb
   41 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/nodes/stream.rb
   42 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/nodes/document.rb
   43 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/nodes/sequence.rb
   44 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/nodes/scalar.rb
   45 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/nodes/mapping.rb
   46 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/nodes/alias.rb
   47 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/nodes.rb
   48 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/streaming.rb
   49 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/visitors/visitor.rb
   50 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/visitors/to_ruby.rb
   51 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/visitors/emitter.rb
   52 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/handler.rb
   53 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/tree_builder.rb
   54 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb
   55 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/json/ruby_events.rb
   56 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/visitors/json_tree.rb
   57 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/visitors/depth_first.rb
   58 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/visitors.rb
   59 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/parser.rb
   60 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/coder.rb
   61 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/core_ext.rb
   62 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/x86_64-darwin14.0/date_core.bundle
   63 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/date/format.rb
   64 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/date.rb
   65 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/deprecated.rb
   66 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/stream.rb
   67 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/json/yaml_events.rb
   68 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/json/tree_builder.rb
   69 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/json/stream.rb
   70 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych/handlers/document_stream.rb
   71 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych.rb
   72 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/yaml.rb
   73 /Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8/encoding-init.rb
   74 /Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8/oracle_version.rb
   75 /Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8/ocihandle.rb
   76 /Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8/datetime.rb
   77 /Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8/oci8.rb
   78 /Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8/cursor.rb
   79 /Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8/bindtype.rb
   80 /Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8/metadata.rb
   81 /Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8/compat.rb
   82 /Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8/object.rb
   83 /Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8/connection_pool.rb
   84 /Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8/properties.rb
   85 /Users/joel/.rvm/gems/ruby-2.1.3/gems/ruby-oci8-2.1.7/lib/oci8.rb
   86 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/x86_64-darwin14.0/bigdecimal.bundle
   87 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/time.rb
   88 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/uri/common.rb
   89 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/uri/generic.rb
   90 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/uri/ftp.rb
   91 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/uri/http.rb
   92 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/uri/https.rb
   93 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/uri/ldap.rb
   94 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/uri/ldaps.rb
   95 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/uri/mailto.rb
   96 /Users/joel/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/uri.rb
   97 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/deprecated.rb
   98 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/sql.rb
   99 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/connection_pool.rb
  100 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/exceptions.rb
  101 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/dataset/query.rb
  102 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/dataset/actions.rb
  103 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/dataset/features.rb
  104 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/dataset/graph.rb
  105 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/dataset/prepared_statements.rb
  106 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/dataset/misc.rb
  107 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/dataset/mutation.rb
  108 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/dataset/sql.rb
  109 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/dataset/placeholder_literalizer.rb
  110 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/dataset.rb
  111 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/database/connecting.rb
  112 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/database/dataset.rb
  113 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/database/dataset_defaults.rb
  114 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/database/logging.rb
  115 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/database/features.rb
  116 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/database/misc.rb
  117 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/database/query.rb
  118 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/database/transactions.rb
  119 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/database/schema_generator.rb
  120 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/database/schema_methods.rb
  121 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/database.rb
  122 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/timezones.rb
  123 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/ast_transformer.rb
  124 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/version.rb
  125 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/core.rb
  126 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/model/default_inflections.rb
  127 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/model/inflections.rb
  128 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/model/plugins.rb
  129 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/model/dataset_module.rb
  130 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/model/base.rb
  131 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/model/exceptions.rb
  132 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/model/errors.rb
  133 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/model/associations.rb
  134 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel/model.rb
  135 /Users/joel/.rvm/gems/ruby-2.1.3/gems/sequel-4.17.0/lib/sequel.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6
```

**Comment by joelw** [comment]
Ah, on further inspection this is a duplicate of issue 32 and 41 and is also caused by LDAP functions. Ensuring that oci8 is loaded first appears to fix it.
