### ISSUE TITLE
Installation with Homebrew libraries on MacOS X 10.11 (El Capitan) Fails with Ruby 2.2.1

### ISSUE THREAD

**Issue by SeanSith** [kubo/ruby-oci8#94]
After attempting installation using the MacOS installation document using the libraries provided by Homebrew, an installation of the latest version of ruby-oci8 on Ruby 2.2.1 and 2.2.3 fail.

Please note that I have DYLD_LIBRARY_PATH set at the command line when attempting installation of the gem. The output claims otherwise. Additionally, it's not entirely clear what/if anything I should set 
ORACLE_HOME to be when using the Homebrew libraries.
```
$ DYLD_LIBRARY_PATH=$(brew --prefix)/lib gem install ruby-oci8
/Users/ssmith/.rbenv/versions/2.2.1/bin/ruby -r ./siteconf20150930-7200-kli76t.rb extconf.rb
checking for load library path... 
  DYLD_LIBRARY_PATH is not set.
checking for cc... ok
checking for gcc... yes
checking for LP64... yes
checking for sys/types.h... yes
checking for ruby header... ok
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/ssmith/.rbenv/versions/2.2.1/bin/$(RUBY_BASE_NAME)
	--with-instant-client
	--without-instant-client
/Users/ssmith/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/ruby-oci8-2.1.8/ext/oci8/oraconf.rb:891:in `get_home': RuntimeError (RuntimeError)
	from /Users/ssmith/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/ruby-oci8-2.1.8/ext/oci8/oraconf.rb:707:in `initialize'
	from /Users/ssmith/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/ruby-oci8-2.1.8/ext/oci8/oraconf.rb:320:in `new'
	from /Users/ssmith/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/ruby-oci8-2.1.8/ext/oci8/oraconf.rb:320:in `get'
	from extconf.rb:18:in `<main>'
---------------------------------------------------
Error Message:
  Set the environment variable ORACLE_HOME if Oracle Full Client.
  Append the path of Oracle client libraries to DYLD_LIBRARY_PATH if Oracle Instant Client.
  
Backtrace:
  /Users/ssmith/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/ruby-oci8-2.1.8/ext/oci8/oraconf.rb:891:in `get_home'
  /Users/ssmith/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/ruby-oci8-2.1.8/ext/oci8/oraconf.rb:707:in `initialize'
  /Users/ssmith/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/ruby-oci8-2.1.8/ext/oci8/oraconf.rb:320:in `new'
  /Users/ssmith/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/ruby-oci8-2.1.8/ext/oci8/oraconf.rb:320:in `get'
  extconf.rb:18:in `<main>'
---------------------------------------------------
See:
 * http://rubydoc.info/gems/ruby-oci8/file/docs/install-full-client.md for Oracle full client
 * http://rubydoc.info/gems/ruby-oci8/file/docs/install-instant-client.md for Oracle instant client
 * http://ruby-oci8.rubyforge.org/en/file.report-installation-issue.html to report an issue.


extconf failed, exit code 1
```

mkmf.log output:
```
"clang -o conftest -I/Users/ssmith/.rbenv/versions/2.2.1/include/ruby-2.2.0/x86_64-darwin14 -I/Users/ssmith/.rbenv/versions/2.2.1/include/ruby-2.2.0/ruby/backward -I/Users/ssmith/.rbenv/versions/2.2.1/include/ruby-2.2.0 -I. -I/Users/ssmith/.rbenv/versions/2.2.1/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/Users/ssmith/.rbenv/versions/2.2.1/lib -L. -L/Users/ssmith/.rbenv/versions/2.2.1/lib  -fstack-protector -L/usr/local/lib     -lruby-static -framework CoreFoundation  -lpthread -lgmp -ldl -lobjc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"clang -o conftest -I/Users/ssmith/.rbenv/versions/2.2.1/include/ruby-2.2.0/x86_64-darwin14 -I/Users/ssmith/.rbenv/versions/2.2.1/include/ruby-2.2.0/ruby/backward -I/Users/ssmith/.rbenv/versions/2.2.1/include/ruby-2.2.0 -I. -I/Users/ssmith/.rbenv/versions/2.2.1/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/Users/ssmith/.rbenv/versions/2.2.1/lib -L. -L/Users/ssmith/.rbenv/versions/2.2.1/lib  -fstack-protector -L/usr/local/lib     -lruby-static -framework CoreFoundation  -lpthread -lgmp -ldl -lobjc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main() { return 0; }
/* end */

./conftest
"clang -I/Users/ssmith/.rbenv/versions/2.2.1/include/ruby-2.2.0/x86_64-darwin14 -I/Users/ssmith/.rbenv/versions/2.2.1/include/ruby-2.2.0/ruby/backward -I/Users/ssmith/.rbenv/versions/2.2.1/include/ruby-2.2.0 -I. -I/Users/ssmith/.rbenv/versions/2.2.1/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe   -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: /*top*/
4: #ifndef __GNUC__
5: # error
6: |:/ === __GNUC__ undefined === /:|
7: #endif
/* end */

"clang -o conftest -I/Users/ssmith/.rbenv/versions/2.2.1/include/ruby-2.2.0/x86_64-darwin14 -I/Users/ssmith/.rbenv/versions/2.2.1/include/ruby-2.2.0/ruby/backward -I/Users/ssmith/.rbenv/versions/2.2.1/include/ruby-2.2.0 -I. -I/Users/ssmith/.rbenv/versions/2.2.1/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/Users/ssmith/.rbenv/versions/2.2.1/lib -L. -L/Users/ssmith/.rbenv/versions/2.2.1/lib  -fstack-protector -L/usr/local/lib     -lruby-static -framework CoreFoundation  -lpthread -lgmp -ldl -lobjc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main() { return sizeof(long) == 8 ? 0 : 1; }
/* end */

./conftest
have_header: checking for sys/types.h... -------------------- yes

"clang -E -I/Users/ssmith/.rbenv/versions/2.2.1/include/ruby-2.2.0/x86_64-darwin14 -I/Users/ssmith/.rbenv/versions/2.2.1/include/ruby-2.2.0/ruby/backward -I/Users/ssmith/.rbenv/versions/2.2.1/include/ruby-2.2.0 -I. -I/Users/ssmith/.rbenv/versions/2.2.1/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <sys/types.h>
/* end */

--------------------
```

**Comment by kubo** [comment]
Wait a moment.
This issue will be fixed in ruby-oci8 2.2.0, which will be released at the next weekend.

If you can't wait, look at https://github.com/kubo/ruby-oci8/issues/89#issuecomment-141667671

**Comment by m3nd3s** [comment]
I'm having the same problem here. Waiting the new version ;)

**Comment by SeanSith** [comment]
@m3nd3s If you can't wait, see #89 as @kubo suggests above and my updated MacOS install instructions in #95. You do NOT want to do the manual installation, as DYLD_LIBRARY_PATH is now a protected variable in El Capitan.

**Comment by m3nd3s** [comment]
@SeanSith Thanks! I'll try!

**Comment by kubo** [comment]
Ruby-oci8 2.2.0 was released. It works on OS X 10.11 El Capitan.
Look at http://www.rubydoc.info/github/kubo/ruby-oci8/master/file/docs/install-on-osx.md.

**Comment by paulolellis** [comment]
Checking the error message worked:

Error Message:
  The output of "otool -L /Library/Oracle/instantclient_11_2/libclntsh.dylib.11.1" is:
    | /Library/Oracle/instantclient_11_2/libclntsh.dylib.11.1:
    | 	/ade/b/3071542110/oracle/rdbms/lib/libclntsh.dylib.11.1 (compatibility version 0.0.0, current version 0.0.0)
    | 	/ade/dosulliv_ldapmac/oracle/ldap/lib/libnnz11.dylib (compatibility version 0.0.0, current version 0.0.0)
    | 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
  
  Ruby-oci8 doesn't work without DYLD_LIBRARY_PATH or DYLD_FALLBACK_LIBRARY_PATH
  because the dependent file "/ade/b/3071542110/oracle/rdbms/lib/libclntsh.dylib.11.1" doesn't exist.
  
  If you need to use ruby-oci8 without DYLD_LIBRARY_PATH or DYLD_FALLBACK_LIBRARY_PATH,
  download "fix_oralib.rb" in https://github.com/kubo/fix_oralib_osx
  and execute it in the directory "/Library/Oracle/instantclient_11_2" as follows to fix the path.
  
**    cd /Library/Oracle/instantclient_11_2
    curl -O https://raw.githubusercontent.com/kubo/fix_oralib_osx/master/fix_oralib.rb
    ruby fix_oralib.rb
  
**  Note: DYLD_* environment variables are unavailable for security reasons on OS X 10.11 El Capitan.



The issue I was having is that the DYLD_LIBRARY_PATH environment variable is no longer good to use, so you have to replace it by the OCI_DIR:

in my case , I installed the client as root under the folder '/Library/Oracle/instantclient_11_2/', so I did was:

$ bundle
<failed>
$ export OCI_DIR=/Library/Oracle/instantclient_11_2/
$ cd $OCI_DIR
$ sudo curl -O https://raw.githubusercontent.com/kubo/fix_oralib_osx/master/fix_oralib.rb
$ sudo rails fix_oralib.rb

and voilá

$ cd -
$ bundle
Fetching gem metadata from https://rubygems.org/...........
(...)
Installing ruby-oci8 2.2.1 with native extensions
(...)
Bundle complete! 14 Gemfile dependencies, 57 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

**Comment by ClouDevops101** [comment]
the link no longer exist (X) https://raw.githubusercontent.com/kubo/fix_oralib_osx/master/fix_oralib.rb

**Comment by kubo** [comment]
@ClouDevops101 
The link is too old. `fix_oralib.rb` is for Oracle instant client 11.2.
